name: Update News

on:
  schedule:
    - cron: '*/10 * * * *'  # כל 10 דקות
  workflow_dispatch:  # אפשר להפעיל ידנית גם אם תרצה

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch RSS Feed
        run: |
          curl -s https://www.ynet.co.il/Integration/StoryRss2.xml | xmllint --format - > news.xml

      - name: Update HTML with New Article
        run: |
          TITLE=$(grep -oPm1 "(?<=<title>)(.*)(?=</title>)" news.xml | head -n 1)
          SUMMARY=$(grep -oPm1 "(?<=<description>)(.*)(?=</description>)" news.xml | head -n 1)
          LINK=$(grep -oPm1 "(?<=<link>)(.*)(?=</link>)" news.xml | head -n 1)
          
          echo "<div class='news-item'><h3>${TITLE}</h3><p>${SUMMARY}</p><a href='${LINK}' target='_blank'>לקריאת הכתבה המלאה</a><hr/></div>" >> news.html

      - name: Commit and Push changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add news.html
          git commit -m "עדכון אוטומטי של חדשות"
          git push
